(function extendNullaI18n(root) {
  'use strict';
  const base = root.NULLA_I18N;
  if (!base) throw new Error('NULLA_I18N must load before runtime-i18n.js');
  const runtime = {
    es:{atoms:'{count} ÁTOMOS',waiting:'EN ESPERA',selectFusion:'Selecciona exactamente 2 elementos',selectFission:'Selecciona U, Pu o Cf',noSuggestion:'Selecciona elementos en la bandeja para ver sugerencias verificadas.',recordUnavailable:'🎥 NO DISPONIBLE',recordStop:'⏹ DETENER',phaseUnknown:'FASE NO MODELADA',phaseUnavailable:'DATOS DE FASE NO DISPONIBLES',phaseSolid:'SÓLIDO',phaseLiquid:'LÍQUIDO',phaseGas:'GAS',favorable:'FAVORABLE',unfavorable:'DESFAVORABLE'},
    en:{atoms:'{count} ATOMS',waiting:'WAITING',selectFusion:'Select exactly 2 elements',selectFission:'Select U, Pu, or Cf',noSuggestion:'Select tray elements to see verified suggestions.',recordUnavailable:'🎥 UNAVAILABLE',recordStop:'⏹ STOP',phaseUnknown:'PHASE NOT MODELED',phaseUnavailable:'PHASE DATA UNAVAILABLE',phaseSolid:'SOLID',phaseLiquid:'LIQUID',phaseGas:'GAS',favorable:'FAVORABLE',unfavorable:'UNFAVORABLE'},
    ja:{atoms:'原子 {count} 個',waiting:'待機中',selectFusion:'元素を2つ選択してください',selectFission:'U、Pu、Cfを選択してください',noSuggestion:'検証済み候補を見るにはトレイの元素を選択してください。',recordUnavailable:'🎥 利用不可',recordStop:'⏹ 停止',phaseUnknown:'未モデル化の相',phaseUnavailable:'相データなし',phaseSolid:'固体',phaseLiquid:'液体',phaseGas:'気体',favorable:'有利',unfavorable:'不利'},
    ru:{atoms:'АТОМОВ: {count}',waiting:'ОЖИДАНИЕ',selectFusion:'Выберите ровно 2 элемента',selectFission:'Выберите U, Pu или Cf',noSuggestion:'Выберите элементы в лотке для проверенных вариантов.',recordUnavailable:'🎥 НЕДОСТУПНО',recordStop:'⏹ ОСТАНОВИТЬ',phaseUnknown:'ФАЗА НЕ СМОДЕЛИРОВАНА',phaseUnavailable:'НЕТ ДАННЫХ О ФАЗЕ',phaseSolid:'ТВЁРДОЕ',phaseLiquid:'ЖИДКОСТЬ',phaseGas:'ГАЗ',favorable:'БЛАГОПРИЯТНО',unfavorable:'НЕБЛАГОПРИЯТНО'},
    zh:{atoms:'{count} 个原子',waiting:'等待中',selectFusion:'请选择恰好两个元素',selectFission:'请选择 U、Pu 或 Cf',noSuggestion:'请选择托盘中的元素以查看已验证建议。',recordUnavailable:'🎥 不可用',recordStop:'⏹ 停止',phaseUnknown:'未建模相态',phaseUnavailable:'无相态数据',phaseSolid:'固态',phaseLiquid:'液态',phaseGas:'气态',favorable:'有利',unfavorable:'不利'},
    fr:{atoms:'{count} ATOMES',waiting:'EN ATTENTE',selectFusion:'Sélectionnez exactement 2 éléments',selectFission:'Sélectionnez U, Pu ou Cf',noSuggestion:'Sélectionnez des éléments pour voir les suggestions vérifiées.',recordUnavailable:'🎥 INDISPONIBLE',recordStop:'⏹ ARRÊTER',phaseUnknown:'PHASE NON MODÉLISÉE',phaseUnavailable:'DONNÉES DE PHASE INDISPONIBLES',phaseSolid:'SOLIDE',phaseLiquid:'LIQUIDE',phaseGas:'GAZ',favorable:'FAVORABLE',unfavorable:'DÉFAVORABLE'},
    it:{atoms:'{count} ATOMI',waiting:'IN ATTESA',selectFusion:'Seleziona esattamente 2 elementi',selectFission:'Seleziona U, Pu o Cf',noSuggestion:'Seleziona elementi nel vassoio per suggerimenti verificati.',recordUnavailable:'🎥 NON DISPONIBILE',recordStop:'⏹ ARRESTA',phaseUnknown:'FASE NON MODELLATA',phaseUnavailable:'DATI DI FASE NON DISPONIBILI',phaseSolid:'SOLIDO',phaseLiquid:'LIQUIDO',phaseGas:'GAS',favorable:'FAVOREVOLE',unfavorable:'SFAVOREVOLE'},
    de:{atoms:'{count} ATOME',waiting:'WARTEN',selectFusion:'Genau 2 Elemente auswählen',selectFission:'U, Pu oder Cf auswählen',noSuggestion:'Elemente in der Ablage für geprüfte Vorschläge auswählen.',recordUnavailable:'🎥 NICHT VERFÜGBAR',recordStop:'⏹ STOPP',phaseUnknown:'PHASE NICHT MODELLIERT',phaseUnavailable:'KEINE PHASENDATEN',phaseSolid:'FEST',phaseLiquid:'FLÜSSIG',phaseGas:'GAS',favorable:'GÜNSTIG',unfavorable:'UNGÜNSTIG'},
    pt:{atoms:'{count} ÁTOMOS',waiting:'AGUARDANDO',selectFusion:'Selecione exatamente 2 elementos',selectFission:'Selecione U, Pu ou Cf',noSuggestion:'Selecione elementos na bandeja para sugestões verificadas.',recordUnavailable:'🎥 INDISPONÍVEL',recordStop:'⏹ PARAR',phaseUnknown:'FASE NÃO MODELADA',phaseUnavailable:'DADOS DE FASE INDISPONÍVEIS',phaseSolid:'SÓLIDO',phaseLiquid:'LÍQUIDO',phaseGas:'GÁS',favorable:'FAVORÁVEL',unfavorable:'DESFAVORÁVEL'},
    ko:{atoms:'원자 {count}개',waiting:'대기 중',selectFusion:'원소를 정확히 2개 선택하세요',selectFission:'U, Pu 또는 Cf를 선택하세요',noSuggestion:'검증된 제안을 보려면 트레이 원소를 선택하세요.',recordUnavailable:'🎥 사용 불가',recordStop:'⏹ 중지',phaseUnknown:'모델링되지 않은 상',phaseUnavailable:'상 데이터 없음',phaseSolid:'고체',phaseLiquid:'액체',phaseGas:'기체',favorable:'유리함',unfavorable:'불리함'},
    ar:{atoms:'{count} ذرة',waiting:'في الانتظار',selectFusion:'اختر عنصرين بالضبط',selectFission:'اختر U أو Pu أو Cf',noSuggestion:'اختر عناصر من الصينية لرؤية اقتراحات موثقة.',recordUnavailable:'🎥 غير متاح',recordStop:'⏹ إيقاف',phaseUnknown:'طور غير ممثل',phaseUnavailable:'بيانات الطور غير متاحة',phaseSolid:'صلب',phaseLiquid:'سائل',phaseGas:'غاز',favorable:'ملائم',unfavorable:'غير ملائم'}
  };
  const extendedKeys = [
    'confinementIllustration','scissionIllustration','blockedDomainMismatch','fusionRoutesHint','isotopesPreview','fusionRouteUncatalogued','noInventedNuclearProduct','tryFusionRoutes','blockedNoEvaluatedChannel','singleIsotopePerChannel','extraReactantsPreserved','balancedRepresentativeChannels',
    'graphicsQualityApplied','pixelRatio','rendererResolutionUpdated','activeStatus','shareTitle','shareSheetOpened','stateUrl','sharedStateContents','sharedStatus','shareUrlCopied','copiedStatus','copyShareUrlPrompt',
    'webxrUnavailable','immersiveApiUnavailable','webxrCompatibleEnvironment','noSessionStarted','unavailableStatus','immersiveVrUnsupported','compatibleHeadsetMissing','webxrMode','immersiveSessionStarted','stereoRenderingEnabled','headsetSessionConnected','activeXrSession','immersiveSessionEnded','desktopRenderingRestored','headsetDisconnected','sessionEnded','webxrNotStarted','sessionRequestFailed','webxrRequirementsNotMet','noActiveVrSession',
    'thermochemistryUnavailable','productsPathwaysUnavailable','pressureSourceUnavailable','rangeUnavailable','isotopeChannelUnavailable','crossSectionProductsUnavailable','thermalNeutronTarget','distributedYields','multipleBranches'
  ];
  const extendedValues = {
    es:['MODELO DE CONFINAMIENTO · ILUSTRACIÓN','MODELO DE ESCISIÓN · ILUSTRACIÓN','BLOQUEADO · DOMINIOS INCOMPATIBLES','Rutas: H+H, H+B, He+He, C+C','Los isótopos se muestran antes de iniciar','RUTA NO CATALOGADA','No se inventará un producto nuclear','Prueba H+H, H+B, He+He o C+C','BLOQUEADO · CANAL NO EVALUADO','Una selección isotópica por canal','No se ignorarán reactivos adicionales','Canales representativos con balance A/Z','Calidad gráfica aplicada','Relación de píxeles','Resolución del renderizador actualizada','ACTIVO','Estructura 3D de NULLA-LABS','Panel de compartir abierto','URL del estado','Estructura + temperatura + reactivos','COMPARTIDO','URL para compartir copiada','COPIADO','Copia esta URL para compartir:','WebXR no disponible','API immersive-vr no disponible','Usa un navegador HTTPS y visor compatibles','No se inició ninguna sesión','NO DISPONIBLE','immersive-vr no es compatible','No se detectó un visor compatible','Modo WebXR VR','Sesión inmersiva iniciada','Renderizado estereoscópico VR activado','Sesión del visor conectada','SESIÓN XR ACTIVA','Sesión inmersiva finalizada','Renderizado de escritorio restaurado','Visor desconectado','SESIÓN FINALIZADA','WebXR no iniciado','Falló la solicitud de sesión','No se cumple un requisito de permiso, HTTPS o dispositivo','No hay sesión VR activa','ΔHf°, Ea y k(T): datos no disponibles','Productos / rutas competidoras: datos no disponibles','p° ≈ 1 atm · fuente no disponible','RANGO NO DISPONIBLE','CANAL ISOTÓPICO: DATOS NO DISPONIBLES','σ(E) / productos: datos no disponibles','nₜₕ + OBJETIVO','RENDIMIENTOS DISTRIBUIDOS · CANAL NO ÚNICO','CONJUNTO DE RAMAS NO ÚNICO'],
    en:['CONFINEMENT MODEL · ILLUSTRATION','SCISSION MODEL · ILLUSTRATION','BLOCKED · DOMAIN MISMATCH','Routes: H+H, H+B, He+He, C+C','Isotopes are shown before starting','UNCATALOGUED ROUTE','No nuclear product will be invented','Try H+H, H+B, He+He, or C+C','BLOCKED · NO EVALUATED CHANNEL','One isotope selection per channel','Additional reactants will not be ignored','Representative channels with A/Z balance','Graphics quality applied','Pixel ratio','Renderer resolution updated','ACTIVE','NULLA-LABS 3D structure','Share sheet opened','State URL','Structure + temperature + reactants','SHARED','Share URL copied','COPIED','Copy this share URL:','WebXR unavailable','No immersive-vr API','Use a compatible HTTPS browser and headset','No session was started','UNAVAILABLE','immersive-vr is not supported','Compatible headset not detected','WebXR VR mode','Immersive session started','VR stereo rendering enabled','Headset session connected','ACTIVE XR SESSION','Immersive session ended','Desktop rendering restored','Headset disconnected','SESSION ENDED','WebXR not started','Session request failed','Permission, HTTPS, or device requirement not met','No active VR session','ΔHf°, Ea, and k(T): data unavailable','Products / competing pathways: data unavailable','p° ≈ 1 atm · source unavailable','RANGE UNAVAILABLE','ISOTOPE CHANNEL: DATA UNAVAILABLE','σ(E) / products: data unavailable','nₜₕ + TARGET','DISTRIBUTED YIELDS · CHANNEL NOT UNIQUE','BRANCH SET NOT UNIQUE'],
    ja:['閉じ込めモデル・模式図','核分裂モデル・模式図','停止・領域不一致','経路: H+H、H+B、He+He、C+C','開始前に同位体を表示します','未登録経路','核生成物を創作しません','H+H、H+B、He+He、C+Cを試してください','停止・未評価チャンネル','チャンネルごとに同位体を1つ選択','追加の反応物は無視されません','A/Z収支を満たす代表チャンネル','描画品質を適用','ピクセル比','レンダラー解像度を更新','有効','NULLA-LABS 3D構造','共有パネルを開きました','状態URL','構造＋温度＋反応物','共有済み','共有URLをコピーしました','コピー済み','この共有URLをコピー:','WebXRは利用できません','immersive-vr APIがありません','対応するHTTPSブラウザーとヘッドセットを使用してください','セッションは開始されませんでした','利用不可','immersive-vrは非対応です','対応ヘッドセットが検出されません','WebXR VRモード','没入型セッションを開始','VRステレオ描画を有効化','ヘッドセットセッション接続','XRセッション有効','没入型セッション終了','デスクトップ描画を復元','ヘッドセット切断','セッション終了','WebXRを開始できません','セッション要求に失敗','権限、HTTPS、または機器要件を満たしていません','有効なVRセッションなし','ΔHf°、Ea、k(T): データなし','生成物／競合経路: データなし','p° ≈ 1 atm・出典なし','範囲データなし','同位体チャンネル: データなし','σ(E)／生成物: データなし','nₜₕ + 標的','収率は分布・チャンネルは一意でない','分岐集合は一意でない'],
    ru:['МОДЕЛЬ УДЕРЖАНИЯ · ИЛЛЮСТРАЦИЯ','МОДЕЛЬ ДЕЛЕНИЯ · ИЛЛЮСТРАЦИЯ','БЛОКИРОВКА · НЕСОВПАДЕНИЕ ОБЛАСТЕЙ','Каналы: H+H, H+B, He+He, C+C','Изотопы показываются до запуска','КАНАЛ НЕ КАТАЛОГИЗИРОВАН','Ядерный продукт не будет выдуман','Попробуйте H+H, H+B, He+He или C+C','БЛОКИРОВКА · КАНАЛ НЕ ОЦЕНЁН','Один выбор изотопа на канал','Дополнительные реагенты не будут игнорироваться','Представительные каналы с балансом A/Z','Качество графики применено','Коэффициент пикселей','Разрешение визуализатора обновлено','АКТИВНО','3D-структура NULLA-LABS','Панель отправки открыта','URL состояния','Структура + температура + реагенты','ОТПРАВЛЕНО','URL скопирован','СКОПИРОВАНО','Скопируйте URL:','WebXR недоступен','Нет API immersive-vr','Используйте совместимый HTTPS-браузер и гарнитуру','Сеанс не запущен','НЕДОСТУПНО','immersive-vr не поддерживается','Совместимая гарнитура не обнаружена','Режим WebXR VR','Иммерсивный сеанс запущен','Стереорендеринг VR включён','Гарнитура подключена','XR-СЕАНС АКТИВЕН','Иммерсивный сеанс завершён','Рендеринг рабочего стола восстановлен','Гарнитура отключена','СЕАНС ЗАВЕРШЁН','WebXR не запущен','Ошибка запроса сеанса','Не выполнено требование разрешения, HTTPS или устройства','Нет активного VR-сеанса','ΔHf°, Ea и k(T): нет данных','Продукты / конкурирующие пути: нет данных','p° ≈ 1 атм · источник недоступен','ДИАПАЗОН НЕДОСТУПЕН','ИЗОТОПНЫЙ КАНАЛ: НЕТ ДАННЫХ','σ(E) / продукты: нет данных','nₜₕ + МИШЕНЬ','РАСПРЕДЕЛЁННЫЕ ВЫХОДЫ · КАНАЛ НЕ ЕДИНСТВЕННЫЙ','НАБОР ВЕТВЕЙ НЕ ЕДИНСТВЕННЫЙ'],
    zh:['约束模型 · 示意图','裂变模型 · 示意图','已阻止 · 领域不匹配','通道：H+H、H+B、He+He、C+C','开始前显示同位素','未编目通道','不会虚构核产物','请尝试 H+H、H+B、He+He 或 C+C','已阻止 · 通道未经评估','每个通道选择一种同位素','不会忽略额外反应物','满足A/Z守恒的代表通道','已应用图形质量','像素比','已更新渲染器分辨率','已启用','NULLA-LABS 三维结构','已打开分享面板','状态URL','结构＋温度＋反应物','已分享','分享URL已复制','已复制','复制此分享URL：','WebXR不可用','无 immersive-vr API','请使用兼容的HTTPS浏览器和头显','未启动会话','不可用','不支持 immersive-vr','未检测到兼容头显','WebXR VR模式','沉浸式会话已启动','已启用VR立体渲染','头显会话已连接','XR会话活跃','沉浸式会话已结束','已恢复桌面渲染','头显已断开','会话已结束','WebXR未启动','会话请求失败','未满足权限、HTTPS或设备要求','无活动VR会话','ΔHf°、Ea和k(T)：无数据','产物／竞争路径：无数据','p° ≈ 1 atm · 无来源数据','范围数据不可用','同位素通道：无数据','σ(E)／产物：无数据','nₜₕ + 靶核','产额呈分布 · 通道不唯一','分支集合不唯一'],
    fr:['MODÈLE DE CONFINEMENT · ILLUSTRATION','MODÈLE DE SCISSION · ILLUSTRATION','BLOQUÉ · DOMAINES INCOMPATIBLES','Voies : H+H, H+B, He+He, C+C','Les isotopes sont affichés avant le lancement','VOIE NON CATALOGUÉE','Aucun produit nucléaire ne sera inventé','Essayez H+H, H+B, He+He ou C+C','BLOQUÉ · CANAL NON ÉVALUÉ','Une sélection isotopique par canal','Les réactifs supplémentaires ne seront pas ignorés','Canaux représentatifs avec bilan A/Z','Qualité graphique appliquée','Rapport de pixels','Résolution du moteur mise à jour','ACTIF','Structure 3D NULLA-LABS','Panneau de partage ouvert','URL de l’état','Structure + température + réactifs','PARTAGÉ','URL de partage copiée','COPIÉ','Copiez cette URL de partage :','WebXR indisponible','API immersive-vr absente','Utilisez un navigateur HTTPS et un casque compatibles','Aucune session démarrée','INDISPONIBLE','immersive-vr non pris en charge','Aucun casque compatible détecté','Mode WebXR VR','Session immersive démarrée','Rendu stéréo VR activé','Session du casque connectée','SESSION XR ACTIVE','Session immersive terminée','Rendu de bureau restauré','Casque déconnecté','SESSION TERMINÉE','WebXR non démarré','Échec de la demande de session','Exigence de permission, HTTPS ou appareil non satisfaite','Aucune session VR active','ΔHf°, Ea et k(T) : données indisponibles','Produits / voies concurrentes : données indisponibles','p° ≈ 1 atm · source indisponible','PLAGE INDISPONIBLE','CANAL ISOTOPIQUE : DONNÉES INDISPONIBLES','σ(E) / produits : données indisponibles','nₜₕ + CIBLE','RENDEMENTS DISTRIBUÉS · CANAL NON UNIQUE','ENSEMBLE DE BRANCHES NON UNIQUE'],
    it:['MODELLO DI CONFINAMENTO · ILLUSTRAZIONE','MODELLO DI SCISSIONE · ILLUSTRAZIONE','BLOCCATO · DOMINI INCOMPATIBILI','Canali: H+H, H+B, He+He, C+C','Gli isotopi sono mostrati prima dell’avvio','CANALE NON CATALOGATO','Non verrà inventato alcun prodotto nucleare','Prova H+H, H+B, He+He o C+C','BLOCCATO · CANALE NON VALUTATO','Una selezione isotopica per canale','I reagenti aggiuntivi non saranno ignorati','Canali rappresentativi con bilancio A/Z','Qualità grafica applicata','Rapporto pixel','Risoluzione del renderer aggiornata','ATTIVO','Struttura 3D NULLA-LABS','Pannello di condivisione aperto','URL dello stato','Struttura + temperatura + reagenti','CONDIVISO','URL di condivisione copiato','COPIATO','Copia questo URL:','WebXR non disponibile','API immersive-vr assente','Usa browser HTTPS e visore compatibili','Nessuna sessione avviata','NON DISPONIBILE','immersive-vr non supportato','Visore compatibile non rilevato','Modalità WebXR VR','Sessione immersiva avviata','Rendering stereo VR attivato','Sessione del visore connessa','SESSIONE XR ATTIVA','Sessione immersiva terminata','Rendering desktop ripristinato','Visore disconnesso','SESSIONE TERMINATA','WebXR non avviato','Richiesta di sessione fallita','Requisito di permesso, HTTPS o dispositivo non soddisfatto','Nessuna sessione VR attiva','ΔHf°, Ea e k(T): dati non disponibili','Prodotti / vie concorrenti: dati non disponibili','p° ≈ 1 atm · fonte non disponibile','INTERVALLO NON DISPONIBILE','CANALE ISOTOPICO: DATI NON DISPONIBILI','σ(E) / prodotti: dati non disponibili','nₜₕ + BERSAGLIO','RESE DISTRIBUITE · CANALE NON UNICO','INSIEME DI RAMI NON UNICO'],
    de:['EINSCHLUSSMODELL · ILLUSTRATION','SPALTUNGSMODELL · ILLUSTRATION','BLOCKIERT · DOMÄNENKONFLIKT','Kanäle: H+H, H+B, He+He, C+C','Isotope werden vor dem Start angezeigt','NICHT KATALOGISIERTER KANAL','Es wird kein Kernprodukt erfunden','H+H, H+B, He+He oder C+C versuchen','BLOCKIERT · KANAL NICHT AUSGEWERTET','Eine Isotopenauswahl je Kanal','Zusätzliche Reaktanten werden nicht ignoriert','Repräsentative Kanäle mit A/Z-Bilanz','Grafikqualität angewendet','Pixelverhältnis','Renderer-Auflösung aktualisiert','AKTIV','NULLA-LABS-3D-Struktur','Teilen-Dialog geöffnet','Zustands-URL','Struktur + Temperatur + Reaktanten','GETEILT','Freigabe-URL kopiert','KOPIERT','Diese Freigabe-URL kopieren:','WebXR nicht verfügbar','Keine immersive-vr-API','Kompatiblen HTTPS-Browser und Headset verwenden','Keine Sitzung gestartet','NICHT VERFÜGBAR','immersive-vr wird nicht unterstützt','Kein kompatibles Headset erkannt','WebXR-VR-Modus','Immersive Sitzung gestartet','VR-Stereodarstellung aktiviert','Headset-Sitzung verbunden','XR-SITZUNG AKTIV','Immersive Sitzung beendet','Desktopdarstellung wiederhergestellt','Headset getrennt','SITZUNG BEENDET','WebXR nicht gestartet','Sitzungsanfrage fehlgeschlagen','Berechtigungs-, HTTPS- oder Geräteanforderung nicht erfüllt','Keine aktive VR-Sitzung','ΔHf°, Ea und k(T): Daten nicht verfügbar','Produkte / konkurrierende Pfade: Daten nicht verfügbar','p° ≈ 1 atm · Quelle nicht verfügbar','BEREICH NICHT VERFÜGBAR','ISOTOPENKANAL: DATEN NICHT VERFÜGBAR','σ(E) / Produkte: Daten nicht verfügbar','nₜₕ + ZIEL','VERTEILTE AUSBEUTEN · KANAL NICHT EINDEUTIG','VERZWEIGUNGSMENGE NICHT EINDEUTIG'],
    pt:['MODELO DE CONFINAMENTO · ILUSTRAÇÃO','MODELO DE CISÃO · ILUSTRAÇÃO','BLOQUEADO · DOMÍNIOS INCOMPATÍVEIS','Rotas: H+H, H+B, He+He, C+C','Os isótopos são mostrados antes do início','ROTA NÃO CATALOGADA','Nenhum produto nuclear será inventado','Tente H+H, H+B, He+He ou C+C','BLOQUEADO · CANAL NÃO AVALIADO','Uma seleção isotópica por canal','Reagentes adicionais não serão ignorados','Canais representativos com balanço A/Z','Qualidade gráfica aplicada','Proporção de pixels','Resolução do renderizador atualizada','ATIVO','Estrutura 3D NULLA-LABS','Painel de compartilhamento aberto','URL do estado','Estrutura + temperatura + reagentes','COMPARTILHADO','URL de compartilhamento copiada','COPIADO','Copie esta URL:','WebXR indisponível','API immersive-vr ausente','Use navegador HTTPS e headset compatíveis','Nenhuma sessão foi iniciada','INDISPONÍVEL','immersive-vr não é compatível','Headset compatível não detectado','Modo WebXR VR','Sessão imersiva iniciada','Renderização estéreo VR ativada','Sessão do headset conectada','SESSÃO XR ATIVA','Sessão imersiva encerrada','Renderização de desktop restaurada','Headset desconectado','SESSÃO ENCERRADA','WebXR não iniciado','Falha na solicitação de sessão','Requisito de permissão, HTTPS ou dispositivo não atendido','Nenhuma sessão VR ativa','ΔHf°, Ea e k(T): dados indisponíveis','Produtos / vias concorrentes: dados indisponíveis','p° ≈ 1 atm · fonte indisponível','FAIXA INDISPONÍVEL','CANAL ISOTÓPICO: DADOS INDISPONÍVEIS','σ(E) / produtos: dados indisponíveis','nₜₕ + ALVO','RENDIMENTOS DISTRIBUÍDOS · CANAL NÃO ÚNICO','CONJUNTO DE RAMOS NÃO ÚNICO'],
    ko:['가둠 모델 · 도해','핵분열 모델 · 도해','차단됨 · 영역 불일치','경로: H+H, H+B, He+He, C+C','시작 전에 동위원소를 표시합니다','미등재 경로','핵 생성물을 임의로 만들지 않습니다','H+H, H+B, He+He 또는 C+C를 사용하세요','차단됨 · 미평가 채널','채널당 동위원소 하나 선택','추가 반응물은 무시되지 않습니다','A/Z 균형을 갖춘 대표 채널','그래픽 품질 적용됨','픽셀 비율','렌더러 해상도 업데이트됨','활성','NULLA-LABS 3D 구조','공유 패널 열림','상태 URL','구조 + 온도 + 반응물','공유됨','공유 URL 복사됨','복사됨','이 공유 URL을 복사하세요:','WebXR 사용 불가','immersive-vr API 없음','호환 HTTPS 브라우저와 헤드셋을 사용하세요','세션이 시작되지 않았습니다','사용 불가','immersive-vr 미지원','호환 헤드셋 미감지','WebXR VR 모드','몰입형 세션 시작됨','VR 스테레오 렌더링 활성화','헤드셋 세션 연결됨','XR 세션 활성','몰입형 세션 종료됨','데스크톱 렌더링 복원됨','헤드셋 연결 해제','세션 종료','WebXR 시작 안 됨','세션 요청 실패','권한, HTTPS 또는 장치 요구사항 미충족','활성 VR 세션 없음','ΔHf°, Ea, k(T): 데이터 없음','생성물 / 경쟁 경로: 데이터 없음','p° ≈ 1 atm · 출처 없음','범위 데이터 없음','동위원소 채널: 데이터 없음','σ(E) / 생성물: 데이터 없음','nₜₕ + 표적','수율 분포 · 채널이 고유하지 않음','분기 집합이 고유하지 않음'],
    ar:['نموذج الحصر · رسم توضيحي','نموذج الانشطار · رسم توضيحي','محظور · عدم تطابق المجالات','المسارات: H+H وH+B وHe+He وC+C','تُعرض النظائر قبل البدء','مسار غير مفهرس','لن يُختلق ناتج نووي','جرّب H+H أو H+B أو He+He أو C+C','محظور · قناة غير مقيّمة','اختيار نظير واحد لكل قناة','لن تُتجاهل المتفاعلات الإضافية','قنوات تمثيلية متوازنة A/Z','طُبقت جودة الرسوم','نسبة البكسل','حُدثت دقة التصيير','نشط','بنية NULLA-LABS ثلاثية الأبعاد','فُتحت لوحة المشاركة','رابط الحالة','البنية + الحرارة + المتفاعلات','تمت المشاركة','نُسخ رابط المشاركة','تم النسخ','انسخ رابط المشاركة:','WebXR غير متاح','لا توجد واجهة immersive-vr','استخدم متصفح HTTPS وخوذة متوافقين','لم تبدأ جلسة','غير متاح','immersive-vr غير مدعوم','لم تُكتشف خوذة متوافقة','وضع WebXR VR','بدأت الجلسة الغامرة','فُعل التصيير المجسم VR','اتصلت جلسة الخوذة','جلسة XR نشطة','انتهت الجلسة الغامرة','استُعيد تصيير سطح المكتب','انفصلت الخوذة','انتهت الجلسة','لم يبدأ WebXR','فشل طلب الجلسة','لم يتحقق شرط الإذن أو HTTPS أو الجهاز','لا توجد جلسة VR نشطة','ΔHf° وEa وk(T): البيانات غير متاحة','النواتج / المسارات المنافسة: البيانات غير متاحة','p° ≈ 1 atm · المصدر غير متاح','النطاق غير متاح','قناة النظائر: البيانات غير متاحة','σ(E) / النواتج: البيانات غير متاحة','nₜₕ + الهدف','نواتج موزعة · القناة غير فريدة','مجموعة الفروع غير فريدة']
  };
  for (const [locale, translations] of Object.entries(extendedValues)) {
    if (translations.length !== extendedKeys.length) throw new Error(`Extended runtime translation count mismatch for ${locale}`);
    Object.assign(runtime[locale], Object.fromEntries(extendedKeys.map((key, index) => [key, translations[index]])));
  }
  Object.entries(runtime).forEach(([locale, catalog]) => Object.assign(base.messages[locale], catalog));
  let currentLocale = 'es';
  root.addEventListener('nulla:locale', event => { currentLocale = base.normalize(event.detail.locale); });
  const t = (key, variables = {}) => {
    const template = base.messages[currentLocale]?.[key] ?? base.messages.en[key] ?? key;
    return String(template).replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? `{${name}}`);
  };
  root.NULLA_I18N = Object.freeze({languages:base.languages,messages:base.messages,apply:base.apply,normalize:base.normalize,t,get locale(){return currentLocale;}});
})(globalThis);
